version: "3.8"

services:
  prism:
    image: stoplight/prism:4
    command: "mock -h 0.0.0.0 --spec https://raw.githubusercontent.com/Morinslash/Prism-POC/master/PrismTest/openapi/test-api.yaml"
    ports:
      - '4010:4010'