name: prism-test
on:
  push
  
jobs:
  prism-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix: 
        dotnet-version: ['6.0.x']   
    services:
      prism:
        image: stoplight/prism:4
        options: -v ${{ github.workspace }}/PrismTest/openapi:/tmp/ --entrypoint "mock -h 0.0.0.0 /tmp/test-api.yaml"
        ports:
          - 4010:4010
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: restart prism
        uses: docker://docker
        with:
          args: docker restart prism
      - run: dotnet restore
        shell: bash
      - run: dotnet test
        shell: bash