name: prism-test
on:
  push

jobs:
  prism-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
    steps:
      - uses: actions/checkout@v2
      - name: printfile
      - run: |
          echo ${{secrets.hello}} >> hello.json
          cat hello.json
